# Site settings
email: "mirche.toshevski@gmail.com"
baseurl: ""
paginate: 8
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Mirche<br />Toshevski's<br />Blog
description: '.NET developer, interested in ASP.NET, Xamarin, MSSQL, fan of Doctor Who'
url: "mirchetoshevski.com"
twitter_username: 
default_img: 

# Profile settings
name: "Mirche Toshevski"
profile_img: "../../../../../assets/covers/homer-simpson.jpeg"
profile: '.NET developer, interested in ASP.NET, Xamarin, MSSQL, fan of Doctor Who'
social: 
  github: "https://github.com/neemesis/"

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Plugins
plugins: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
