# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /blog/:year/:month/:day/:title/

# Setup
title:            "Mirche Toshevski"
tagline:          "Mirche Toshevski's Blog"
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:      '.NET developer, interested in <a href="https://www.asp.net/">ASP.NET</a>, <a href="https://www.xamarin.com/">Xamarin</a>, <a href="#">MSSQL</a>, fan of <a href="http://www.bbc.co.uk/programmes/b006q2x0">Doctor Who</a>'
url:              https://neemesis.github.io
baseurl:          /
hometitle:        "Posts"

author:
  name:           'Mirche Toshevski'
  url:            https://www.linkedin.com/in/mirche-toshevski-9918b6108/

paginate:         5

# Custom vars
version:          1.0.0.0

logo:             /assets/home1.jpg

github:
  repo:           https://github.com/neemesis/neemesis.github.io

# Plugins
plugins:          [jekyll-paginate, jekyll-sitemap]