# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Mirche Toshevski Blog"
tagline:          "Mirche Toshevski's Blog"
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:      '.NET developer, interested in <a href="https://www.asp.net/">ASP.NET</a>, <a href="https://www.xamarin.com/">Xamarin</a>, <a href="#">MSSQL</a>, fan of <a href="#">Doctor Who</a>'
url:              https://neemesis.github.io
baseurl:          /

author:
  name:           'Mirche Toshevski'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/neemesis/neemesis.github.io

# Plugins
plugins:          [jekyll-paginate]